var x = fn { throw 1 }

try {
    x()
}
catch {
    print(exception + 2)
    throw 'a'
}
finally {
    print('f')
}